/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as BookNoRouteImport } from './routes/$bookNo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookNoIndexRouteImport } from './routes/$bookNo.index'
import { Route as BookNoChapterNoRouteImport } from './routes/$bookNo.$chapterNo'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const BookNoRoute = BookNoRouteImport.update({
  id: '/$bookNo',
  path: '/$bookNo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookNoIndexRoute = BookNoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookNoRoute,
} as any)
const BookNoChapterNoRoute = BookNoChapterNoRouteImport.update({
  id: '/$chapterNo',
  path: '/$chapterNo',
  getParentRoute: () => BookNoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$bookNo': typeof BookNoRouteWithChildren
  '/compose': typeof ComposeRoute
  '/search': typeof SearchRoute
  '/$bookNo/$chapterNo': typeof BookNoChapterNoRoute
  '/$bookNo/': typeof BookNoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/search': typeof SearchRoute
  '/$bookNo/$chapterNo': typeof BookNoChapterNoRoute
  '/$bookNo': typeof BookNoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$bookNo': typeof BookNoRouteWithChildren
  '/compose': typeof ComposeRoute
  '/search': typeof SearchRoute
  '/$bookNo/$chapterNo': typeof BookNoChapterNoRoute
  '/$bookNo/': typeof BookNoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$bookNo'
    | '/compose'
    | '/search'
    | '/$bookNo/$chapterNo'
    | '/$bookNo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compose' | '/search' | '/$bookNo/$chapterNo' | '/$bookNo'
  id:
    | '__root__'
    | '/'
    | '/$bookNo'
    | '/compose'
    | '/search'
    | '/$bookNo/$chapterNo'
    | '/$bookNo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookNoRoute: typeof BookNoRouteWithChildren
  ComposeRoute: typeof ComposeRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$bookNo': {
      id: '/$bookNo'
      path: '/$bookNo'
      fullPath: '/$bookNo'
      preLoaderRoute: typeof BookNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$bookNo/': {
      id: '/$bookNo/'
      path: '/'
      fullPath: '/$bookNo/'
      preLoaderRoute: typeof BookNoIndexRouteImport
      parentRoute: typeof BookNoRoute
    }
    '/$bookNo/$chapterNo': {
      id: '/$bookNo/$chapterNo'
      path: '/$chapterNo'
      fullPath: '/$bookNo/$chapterNo'
      preLoaderRoute: typeof BookNoChapterNoRouteImport
      parentRoute: typeof BookNoRoute
    }
  }
}

interface BookNoRouteChildren {
  BookNoChapterNoRoute: typeof BookNoChapterNoRoute
  BookNoIndexRoute: typeof BookNoIndexRoute
}

const BookNoRouteChildren: BookNoRouteChildren = {
  BookNoChapterNoRoute: BookNoChapterNoRoute,
  BookNoIndexRoute: BookNoIndexRoute,
}

const BookNoRouteWithChildren =
  BookNoRoute._addFileChildren(BookNoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookNoRoute: BookNoRouteWithChildren,
  ComposeRoute: ComposeRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
